if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager") 
BiocManager::install(version = "3.12")

BiocManager::install("ComplexHeatmap", force = T)

BiocManager::install(biomaRt, force = T)
BiocManager::install(pathview, force = T)
BiocManager::install(rtracklayer, force = T)
BiocManager::install(DESeq2, force = T)
BiocManager::install(pheatmap, force = T)
BiocManager::install(vcfR, force = T)
BiocManager::install(ballgown, force = T)
BiocManager::install(RColorBrewer, force = T)
BiocManager::install(gplots, force = T)
BiocManager::install(spatstat, force = T)
BiocManager::install(circlize, force = T)
BiocManager::install(GOplot, force = T)
library(biomaRt)
library(pathview)
library(rtracklayer)
library(DESeq2)
library(pheatmap)
library(vcfR)
library(ballgown)
library(RColorBrewer)
library(gplots)
library(spatstat)
library(circlize)
library(GOplot)
